### PR TITLE
add revision per project

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Review by rombert — CHANGES_REQUESTED** [review]
I would prefer that we add this settings only when it differs from the default defined at https://github.com/apache/sling-aggregator/blob/733d9bd483462fcd994ef2bc729bcae82e29ec69/collect-sling-repos.groovy#L93 . This way we have less visual 'noise' in the file.

**Comment by rombert** [comment]
I've pulled in the change manually in #5 so `repo sync` works while we iterate on this, and hopefully get a solution which does not require mixed branch names.

I think this change is still useful since we may choose to transition to a different default branch name and will probably have a mixed setup during the transition.

**Comment by kwin** [comment]
> This way we have less visual 'noise' in the file.

I agree, but I am not familiar with the `MarkupBuilder` in groovy so not sure how to achieve this with no code duplication. Any pointers are appreciated...

**Comment by rombert** [comment]
Maybe settings `omitNullAttributes` to true will help? https://docs.groovy-lang.org/latest/html/api/groovy/xml/MarkupBuilder.html#isOmitNullAttributes() . Then we can define the revision as null if it matches the default or otherwise to its proper value.

**Review by rombert — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
